POST https://sore-gray-oyster-coat.cyclic.app/auth/login
Content-Type: application/json

{
    "username": "Anand",
    "password": "Anand12345"
}

###
GET https://sore-gray-oyster-coat.cyclic.app/blogs/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFuYW5kIiwiZW1haWwiOiJhYWEiLCJwYXNzd29yZCI6IjEyMzQ1IiwiaWF0IjoxNjc1OTU5MjQzfQ.dSwcW8plt_JuXc2YQy8FI0Cai8L16WmM7tGl3xP6dDc
Content-Type: application/json